### ISSUE TITLE
Eliminate F_CPU_CORRECTED

### ISSUE THREAD

**Issue by SimonMerrett** [technoblogy/tiny-mega-i2c#1]
Firstly, thanks *so* much for this library David - saves well over 1kB on my tiny402. I'd like to include it as the default I2C library on my nascent [tinyOLED library](https://github.com/SimonMerrett/tinyOLED) for the new ATtiny 0 and 1 series, driving SSD1306-based OLED displays. 

However, I believe @SpenceKonde [has removed F_CPU_CORRECTED in the most recent commits](https://github.com/SpenceKonde/megaTinyCore/commit/bd9a32070188fae51ec376a12b64548fe821ddde) of megaTinyCore. Would you mind changing line 21 in `TinyMegaI2CMaster.cpp` from:

`uint32_t baud = ((F_CPU_CORRECTED/FREQUENCY) - (((F_CPU_CORRECTED*T_RISE)/1000)/1000)/1000 - 10)/2;`

to:

`uint32_t baud = ((F_CPU/FREQUENCY) - (((F_CPU*T_RISE)/1000)/1000)/1000 - 10)/2;`, which seems to work for me, or something better if F_CPU isn't the best variable to put in there. Thanks again. Please say if you'd like me to go through a full clone and PR submission to make that change, but it seemed so small it wasn't worth doing.

**Comment by SpenceKonde** [comment]
Yup - I have removed F_CPU_CORRECTED. Hans also removed it from his MegaCoreX - it was removed as part of the flash/ram usage optimizations - as it was completely redundant (always had same value as F_CPU, and it wound up eating flash/ram. I am not sure why the official core ever had it in the first place....

I am loathe to add in compatibility features that cater to the strange and ill-advised decisions that the official core made... I am *very* disappointed in the official megaavr package...

**Comment by SimonMerrett** [comment]
Thanks @technoblogy
