### ISSUE TITLE
STOP condition not working

### ISSUE THREAD

**Issue by buckket** [technoblogy/tiny-mega-i2c#3]
First of all thanks for sharing your code. I used it as a starting point for my own project. 

But I have encountered some flaws:

When writing data the code blocks at the beginning of the respective function to wait for the **previous** transmission to complete. This works fine for writing consecutive data, however, when terminating the sequence by issuing a stop condition the code does not wait for the current write transaction to finish and thus the stop condition cannot be sent successfully and the bus stays in the OWNER state until start() is called again which resets the bus.

Sidenote: This also means that TWI_RXACK returned by the write function is invalid or from the previous write since it's read before the write is complete.

Proposed solution: You could either move the polling to the end of the write function, or you only send the stop condition before checking that TWI_CLKHOLD is set. Either way you may even want to poll for the bus returning to the idle state in the stop() function to make sure the STOP condition was definitely sent completely, in case one calls stop() immediately followed by a sleep instruction.

Hope this helps!

**Comment by technoblogy** [comment]
Thank you - I'll investigate.

**Comment by technoblogy** [comment]
Do you have a modification of my code that you've tested?

**Comment by buckket** [comment]
> 
> 
> Do you have a modification of my code that you've tested?

https://gist.github.com/buckket/09619e6cdc5dee056d41bfb57065db81

This is the code I'm using right now. Error handling still leaves much to be desired but reading, writing and stopping works as expected. A write directly followed by a read works fine as well. Here's a screenshot:

![screenshot](https://user-images.githubusercontent.com/111178/110697716-040b1700-81ed-11eb-85b2-ada3fb877ae2.png)

**Comment by technoblogy** [comment]
Hi Felix, I've been having a look at your code and have a couple of comments.

I like what you've done with **TWI0_BAUD**; much neater.

I see what you mean about **TWI0_write()**; I'm waiting for the write to complete before sending the data, which is the wrong way round.

In **TWI0_read()** I'm not sure why you changed the last line:

    TWI0.MCTRLB = TWI_ACKACT_bm | TWI_MCMD_RECVTRANS_gc;

to:

    TWI0.MCTRLB = TWI_ACKACT_NACK_gc;

Was mine incorrect?

Thanks,
David

**Comment by buckket** [comment]
Hi David,

thanks for your feedback.

`TWI_ACKACT_bm` and `TWI_ACKACT_NACK_gc` are equivalent. Both set the Acknowledge Action to NACK.
When writing to `MCMD` in `TWI0.MCTRLB` the queued Acknowledge Action gets executed.

`RECVTRANS` would send the NACK but also start another receive operation, when in fact we want to stop reading.
Thus I only set the Acknowledge Action to NACK there. It will be sent when we follow up on the `TWI0_read()` with either a `TWI0_stop()` or `TWI0_start()`.

The datasheet for the ATtiny817 states:
>The software can prepare to take one of the following actions [after receiving a data packet]:
•  Respond with an ACK by writing ‘0’ to the ACKACT bit in the TWIn.MCTRLB register and prepare to receive a new data packet
•  Respond with a NACK by writing ‘1’ to the ACKACT bit and then transmit a new address packet
•  Respond with a NACK by writing ‘1’ to the ACKACT bit and then complete the transaction by issuing a Stop condition in the MCMD bit field from the TWIn.MCTRLB register

AFAIK your implementation will work fine but consume more CLK cycles, but I can’ŧ remember exactly.

**Comment by technoblogy** [comment]
Thanks. I'll probably go with your version after a bit of testing because I don't have a logic analyser to check it. Thank you for the suggestions!

**Comment by technoblogy** [comment]
Incorporated in Version 1.1.0. Thank you for suggesting this, and sorry it took so long for me to test it and implement it.
