### ISSUE TITLE
Fix missing info & files for making this library usable by arduino-cli

### ISSUE THREAD

**Issue by dattasaurabh82** [technoblogy/tiny-mega-i2c#6]
Hi again. 
Thanks for the great work. 

I was just trying to install lib using **arduino-cli**:
`arduino-cli lib install --git-url https://github.com/technoblogy/tiny-mega-i2c.git -v`

I got the following error:
...
```
...
...
Error installing Git Library: library is not valid: missing header file "tiny-mega-i2c.h"
```

So I renamed the forked repository from: `<GIT_URL>/tiny-mega-i2c` to `<GIT_URL>/TinyMegaI2CMaster` like the names for the src files (`.h` and `.cpp`)

Then I ran the command again (from my forked version with the repository renamed):
`arduino-cli lib install --git-url https://github.com/dattasaurabh82/TinyMegaI2CMaster.git -v`

I got the following error:
```
...
...
Error installing Git Library: library is not valid: missing file "library.properties"
```

So I added a `library.properties` file with teh following content:
```
name=TinyMegaI2CMaster 
version=1.0.0
author=David Johnson-Davies <info@monoton.co>
maintainer=David Johnson-Davies <info@monoton.co> 
sentence=A low footprint i2c lib for mega tiny cores
category=I2C
url=https://github.com/dattasaurabh82/TinyMegaI2CMaster
architectures=*
```

And after running the previous command, the library could now be installed by `arduino-cli lib install --git-url <forked and edited git_url>`

More on proper library specifications are here in the [reference page of arduino-cli](https://arduino.github.io/arduino-cli/latest/library-specification/)

So I hope it would be a great help for the community, if those changes are made to this repo. 🤓

**Comment by technoblogy** [comment]
Incorporated in Version 1.1.0. Thank you for suggesting this, and sorry it took so long for me to test it and implement it.
